server:
  port: 8086 #Tomcat端口
spring:
  dubbo:
    application:
      name: springboot-dubbo-demo #应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20896 #dubbo服务暴露的端口
    scan: com.secoo.user.api #扫描的包名